/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assistcontrol.UI;

import com.mycompany.assistcontrol.Camera;
import com.mycompany.assistcontrol.Time;
import com.mycompany.assistcontrol.Util;
import com.mycompany.assistcontrol.services.userService;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class Assistent extends javax.swing.JFrame implements Runnable, ThreadFactory {

        private static final long serialVersionUID = 6441489157408381878L;
        Camera camera;
        private Executor executor = Executors.newSingleThreadExecutor(this);

        /**
         * Creates new form Assistent
         */
        public Assistent() {
                initComponents();
                setLocationRelativeTo(null);
                setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                camera = new Camera(jPanelCamera);
                executor.execute(this);

                //iniciamos el reloj
                new Time(labelClock);

                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent e) {
                                closeMenu();
                        }
                });

        }

        private void closeMenu() {
                camera.close();
                dispose();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelCamera = new javax.swing.JPanel();
                labelClock = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                result = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanelCamera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanelCamera.setAlignmentX(0.0F);
                jPanelCamera.setAlignmentY(0.0F);

                labelClock.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                labelClock.setText("xx:xx:xx xx");

                jButton1.setText("Salir");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                result.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                result.setText("No se detectó ningún usuario");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jPanelCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelClock, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(result))
                                .addContainerGap(29, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(41, 41, 41))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelClock)
                                                .addGap(26, 26, 26)
                                                .addComponent(result))
                                        .addComponent(jPanelCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(21, 21, 21))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                closeMenu();
        }//GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Assistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Assistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Assistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Assistent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Assistent().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JPanel jPanelCamera;
        private javax.swing.JLabel labelClock;
        private javax.swing.JLabel result;
        // End of variables declaration//GEN-END:variables

        @Override
        public void run() {
                do {

                        try {
                                Thread.sleep(1000);
                        } catch (Exception e) {
                                System.out.println(e.getMessage());
                        }

                        String qrText = camera.getQRText();

                        if (qrText == null) {
                                continue;
                        }

                        var user = userService.findByDni(qrText);

                        if (user == null) {
                                Util.soundError();
                                JOptionPane.showMessageDialog(this, "No se encontró el usuario. Pida a su administrador que le registre a la base de datos");
                                continue;
                        }

                        result.setText(user.getFullname());

                } while (true);
        }

        @Override
        public Thread newThread(Runnable r) {
                Thread t = new Thread(r, "example-runner");
                t.setDaemon(true);
                return t;
        }

}
